apiVersion: v1
kind: Service
metadata:
  name: myhtmlweb
  labels:
    app: webserver
spec:
  ports:
    - port: 4949
      nodePort: 31000
      targetPort: 80
  selector:
    app: webserver
    tier: frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myhtmlweb
  labels:
    app: webserver
spec:
  selector:
    matchLabels:
      app: webserver
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webserver
        tier: frontend
    spec:
      containers:
      - image: httpd
        name: myhtmlweb
        ports:
        - containerPort: 80
          name: webserver
        volumeMounts:
        - name: webstorage
          mountPath: /usr/local/apache2/htdocs/
      volumes:
      - name: webstorage
        persistentVolumeClaim:
          claimName: htmlwebpvc