apiVersion: v1
kind: Service
metadata:
  name: myphpweb
  labels:
    app: webserver
spec:
  ports:
    - port: 4949
      nodePort: 32000
      targetPort: 80
  selector:
    app: webserver
    tier: frontend
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myphpweb
  labels:
    app: webserver
spec:
  selector:
    matchLabels:
      app: webserver
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webserver
        tier: frontend
    spec:
      containers:
      - image: vimal13/apache-webserver-php
        name: myphpweb
        ports:
        - containerPort: 80
          name: webserver
        volumeMounts:
        - name: webstorage
          mountPath: /var/www/html
      volumes:
      - name: webstorage
        persistentVolumeClaim:
          claimName: phpwebpvc